# Generated by Django 3.2 on 2021-07-12 09:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_brand', models.CharField(max_length=100, null=True, verbose_name='Product Brand')),
                ('product_type', models.CharField(max_length=100, verbose_name='Product Type')),
                ('product_url', models.URLField(max_length=2000, null=True, verbose_name='Product URL')),
                ('hair_type', models.CharField(max_length=100, verbose_name='Hair Type')),
                ('hair_texture', models.CharField(max_length=100, verbose_name='Hair Texture')),
                ('hair_porosity', models.CharField(max_length=100, verbose_name='Hair Porosity')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Updated DateTime')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=100, null=True, verbose_name='Product Brand')),
                ('product_url', models.URLField(max_length=2000, null=True, verbose_name='Product URL')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created DateTime')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Updated DateTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
    ]
