# Generated by Django 3.2 on 2021-07-13 09:01

from django.db import migrations, models
import new_tenpadayo.models


class Migration(migrations.Migration):

    dependencies = [
        ('new_tenpadayo', '0004_auto_20210713_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='productid',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.CharField(max_length=200, null=True, verbose_name=new_tenpadayo.models.Product),
        ),
    ]
