# Generated by Django 3.2 on 2021-07-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_tenpadayo', '0005_auto_20210713_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
