# Generated by Django 3.2 on 2021-07-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_tenpadayo', '0008_rename_productid_wishlist_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_name',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_tenpadayo.product'),
        ),
    ]
